/**
 * Shared pattern/data definitions for the scanners.
 * Centralized so rules are easy to audit and tune.
 */

/** Directories we never descend into or fetch. */
export const SKIP_DIRS = [
  "node_modules",
  ".git",
  ".next",
  ".turbo",
  ".cache",
  "dist",
  "build",
  "out",
  "target",
  "vendor",
  "__pycache__",
  ".venv",
  "venv",
  "env",
  ".idea",
  ".vscode",
  "coverage",
  ".gradle",
  ".pytest_cache",
  ".mypy_cache",
  "Pods",
  "bower_components",
  ".terraform",
];

/*
 * Directories that usually hold tests, fixtures, examples, or docs — not the
 * code a user actually runs. We still scan the repo for these (e.g. to detect
 * a tests/ folder as a good signal), but we don't deep-scan their contents,
 * because fixture files routinely contain fake URLs, IPs, and dummy secrets
 * that would flood the report with false positives.
 */
export const NON_SHIPPING_DIRS = [
  "test",
  "tests",
  "__tests__",
  "__mocks__",
  "fixtures",
  "fixture",
  "testdata",
  "test-data",
  "test-utils",
  "testing",
  "scripts",
  "tools",
  "bench",
  "benchmarks",
  "benchmark",
  "fuzz",
  "fuzzer",
  "examples",
  "example",
  "e2e",
  "integration",
  "cypress",
  "playwright",
  "docs",
  "documentation",
  "mocks",
  "stubs",
  "stories",
  "storybook",
  "snapshots",
  ".github",
];

/** Manifest & config files we always fetch when present. */
export const MANIFEST_FILES = new Set([
  // Node
  "package.json",
  ".npmrc",
  ".yarnrc",
  ".yarnrc.yml",
  // Python
  "requirements.txt",
  "requirements-dev.txt",
  "setup.py",
  "setup.cfg",
  "pyproject.toml",
  "Pipfile",
  // Rust
  "Cargo.toml",
  "build.rs",
  // Go
  "go.mod",
  // Ruby
  "Gemfile",
  // PHP
  "composer.json",
  // JVM
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  // Swift
  "Package.swift",
  // Build/lifecycle
  "Makefile",
  "GNUmakefile",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  "CMakeLists.txt",
  "install.sh",
  "setup.sh",
  "configure",
]);

/** README / governance files we always fetch. */
export const DOC_FILES = new Set([
  "README.md",
  "README.rst",
  "README.txt",
  "README",
  "readme.md",
  "readme",
  "SECURITY.md",
  "SECURITY",
  "CONTRIBUTING.md",
  "CONTRIBUTING",
  "LICENSE",
  "LICENSE.md",
  "LICENSE.txt",
  "COPYING",
  "CODE_OF_CONDUCT.md",
]);

/** Source extensions we scan for code patterns. */
export const SOURCE_EXTENSIONS = new Set([
  ".js",
  ".mjs",
  ".cjs",
  ".jsx",
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".py",
  ".pyi",
  ".rb",
  ".go",
  ".rs",
  ".php",
  ".java",
  ".kt",
  ".kts",
  ".swift",
  ".sh",
  ".bash",
  ".zsh",
  ".fish",
  ".ps1",
  ".psm1",
  ".bat",
  ".cmd",
  ".lua",
  ".pl",
  ".pm",
  ".scala",
  ".clj",
  ".cljs",
  ".ex",
  ".exs",
  ".erl",
  ".vim",
  ".jl",
  ".dart",
  ".vue",
  ".svelte",
  ".astro",
  ".gradle",
  ".groovy",
  ".tf",
  ".proto",
  ".cmake",
  ".nim",
  ".zig",
  ".cr",
]);

/** Files that are almost always generated/minified — skip deep scanning. */
export const IGNORE_FILE_RE =
  /\.(min|bundle|bundled|packed|compiled|uglified)\.(js|mjs|cjs|css)$/i;

/** Curated list of frequently-impersonated package names for typo detection. */
export const POPULAR_PACKAGES = [
  // npm
  "react",
  "react-dom",
  "next",
  "vue",
  "vue-router",
  "vuex",
  "@vue/cli",
  "axios",
  "lodash",
  "underscore",
  "express",
  "fastify",
  "koa",
  "chalk",
  "commander",
  "fs-extra",
  "request",
  "moment",
  "dayjs",
  "date-fns",
  "typescript",
  "ts-node",
  "eslint",
  "webpack",
  "vite",
  "rollup",
  "babel",
  "@babel/core",
  "jest",
  "vitest",
  "mocha",
  "chai",
  "dotenv",
  "jsonwebtoken",
  "passport",
  "mongoose",
  "prisma",
  "mongodb",
  "redis",
  "ws",
  "socket.io",
  "gulp",
  "grunt",
  "yeoman",
  "electron",
  "tailwindcss",
  "bootstrap",
  "jquery",
  "three",
  "rxjs",
  "zod",
  "yup",
  "ramda",
  "qs",
  "uuid",
  "nanoid",
  "glob",
  "cheerio",
  "puppeteer",
  "playwright",
  "cors",
  "helmet",
  "morgan",
  "winston",
  "pino",
  "nodemon",
  "concurrently",
  "cross-env",
  "npm",
  "yarn",
  "pnpm",
  // python
  "requests",
  "numpy",
  "pandas",
  "django",
  "flask",
  "fastapi",
  "scipy",
  "matplotlib",
  "scikit-learn",
  "tensorflow",
  "torch",
  "pytorch",
  "beautifulsoup4",
  "selenium",
  "pytest",
  "setuptools",
  "pip",
  "boto3",
  "celery",
  "sqlalchemy",
  "cryptography",
  "pyyaml",
  "tqdm",
  "click",
];

/** Domains/hosts commonly used for payload hosting or data exfiltration. */
export const SUSPICIOUS_HOSTS = [
  "pastebin.com",
  "paste.ee",
  "hastebin.com",
  "0bin.net",
  "zerobin.net",
  "rentry.co",
  "ngrok.io",
  "ngrok.app",
  "ngrok-free.app",
  "bitly.com",
  "bit.ly",
  "tinyurl.com",
  "is.gd",
  "cutt.ly",
  "discord.com",
  "discordapp.com",
  "api.telegram.org",
  "t.me",
  "webhook.site",
  "pipedream.net",
  "requestbin.com",
  "hookbin.com",
  "ipfs.io",
  "ipfs",
  "file.io",
  "ufile.io",
  "anonfiles.com",
  "gofile.io",
  "transfer.sh",
  "0x0.st",
];

/** TLDs that skew toward abuse; flag raw hosts that use them. */
export const SUSPICIOUS_TLDS = [
  ".top",
  ".xyz",
  ".click",
  ".loan",
  ".work",
  ".country",
  ".stream",
  ".download",
  ".review",
  ".gq",
  ".cf",
  ".ml",
  ".tk",
  ".ga",
  ".rest",
  ".buzz",
  ".surf",
  ".quest",
  ".monster",
  ".sbs",
  ".cyou",
  ".cam",
  ".fun",
  ".icu",
  ".live",
  ".casa",
  ".beauty",
  ".fit",
];

/** Commands that, inside an install hook, raise the risk floor. */
export const SUSPICIOUS_COMMANDS = [
  "curl",
  "wget",
  "fetch",
  "nc ",
  "ncat",
  "netcat",
  "ssh",
  "scp",
  "base64",
  "openssl",
  "node -e",
  "node --eval",
  "python -c",
  "python3 -c",
  "python -c",
  "ruby -e",
  "perl -e",
  "php -r",
  "powershell",
  "pwsh",
  "-EncodedCommand",
  "iex",
  "Invoke-Expression",
  "DownloadString",
  "DownloadFile",
  "eval",
  "exec",
  "/dev/tcp",
  "chmod +x",
  "curl -fsSL",
  "nohup",
  "crontab",
];
